### ISSUE TITLE
whenever change channel with up or down, show starts from beginning

### ISSUE THREAD

**Issue by montajd** [Steveb1968/script.pseudotv#11]
Thanks for such a great add-on! It's the only way I can watch all my stuff now. Anywho, I've noticed that if I change to a show/channel via the EPG, most of the time, it will skip to the same progress shown in the EPG. When I change the channel via up and down, it starts the channel's current show from the beginning. It's not that big of a deal, but it does take away from the feeling of actual TV. One more thing, I doubt there's much that can be done about this, but when it seeks to pickup where the show should be, you can still see the Kodi OSD, and covers up the show info, and channel number. Thanks for all the hard work you've put into this. I tried PseudoTV Live, but it has way too much going on, and cannot be compared to the original!

**Comment by montajd** [comment]
Kodi 17 Krypton fixed the issue with the channel changing, and I was able to hide the OSD (using the Estuary skin at least) by adding the line you gave jordanryle <visible>String.IsEmpty(Window(home).Property(PseudoTVRunning))</visible> to DialogSeekBar.xml. Hope this helps others!

**Comment by Steveb1968** [comment]
Sorry I didn't get to you sooner but I'm  glad you got it sorted out.
Kodi 17 Krypton with its updates to the video player is the way to go. ;)
