### ISSUE TITLE
TV Channels Getting Lost on Restart

### ISSUE THREAD

**Issue by montronic** [Steveb1968/script.pseudotv#12]
Hi Does any one know the reason I could be loosing all my channels after I restart Kodi.

I setup all my various channels but after a while when I restart Pseudo Tv goes back to the Default channel listings

**Comment by Steveb1968** [comment]
No sorry, I can't say that I know what's going on there. It's never happened to me or has been reported before. I've had the same channel setup for years, plus or minus the odd channel here and there. ;)
