### ISSUE TITLE
Ability to open menu (player controls) in PTV?

### ISSUE THREAD

**Issue by lzep** [Steveb1968/script.pseudotv#14]
First off, thank you for the continued effort keeping PTV alive and updated!

Is there a way to open the menu (player controls) in PTV so I can change subtitles, audio languages, etc.? I believe it used to be "m" but that doesn't seem to work in Kodi Krypton 17.

Thanks!

**Comment by Steveb1968** [comment]
Yep there sure is. :)
Basically you have to set a global keymap. This is because PseudoTV  has a overlay window to show vid info, channel num, logo., on top of the fullscreen video.
[http://kodi.wiki/view/keymap](http://kodi.wiki/view/keymap)
If you need help with that just let me know.
Cheers

**Comment by lzep** [comment]
Ah, thanks!  So at that keymap url you posted, it seems if you use "OSD" with a global key it should work. But I couldn't get it to pop up, so what I did was bind two different keys to "NextSubtitle" and "AudioNextLanguage" and those seemed to work.

Do you know if there's another command to pop the osd?  If not, I'll stick with the two keys I mapped instead.

Thanks!

**Comment by Steveb1968** [comment]
Something like..
<m mod="ctrl">ActivateWindow(videoosd)</m>
should work but its up to you which key/combo you use. :)
Once the window is open and focused it can be closed with the usual key or esc/back.

**Comment by lzep** [comment]
Awesome, using the ActivateWindow command worked!  Thanks!
