### ISSUE TITLE
Unable to change audio stream

### ISSUE THREAD

**Issue by benoit505** [Steveb1968/script.pseudotv#15]
Hi, I have a lot of movies in my library and most of them have more than one audio stream (different languages) is there a way to change the audiostream? Thx

**Comment by Steveb1968** [comment]
Hi mate, yes there is.. :)
lzep asked a simular question here [https://github.com/Steveb1968/script.pseudotv/issues/14](https://github.com/Steveb1968/script.pseudotv/issues/14)
If you need any extra help, just ask. :)

**Comment by benoit505** [comment]
Oh I didn't see that question! ^^
I'm currently pretty obsessed by this add on and I have another question, I wanted to make a channel from a smartlist, I made a smartlist in kodi of all the movies in the IMDB Top 250 but when i browsed and clicked the smartlist nothing happend :(

Thx for the quick reply and really great work on the add on!!

**Comment by Steveb1968** [comment]
A Top250 playlist should work, I have a movie channel like that. :)
If you can't get it working, post a bit more info on how your trying to creating it.
