### ISSUE TITLE
issues with missing channels/shows

### ISSUE THREAD

**Issue by montajd** [Steveb1968/script.pseudotv#17]
for the life of me, even after completely removing and rescanning my entire library, I am unable to add two specific shows either chalked themselves, or in any other capacity. They do play fine in Kodi, and are in my library. I'm running Krypton 17.6 on Shield TV, Latest PSTV Master.
Thanks!

**Comment by montajd** [comment]
chalked = channels* gotta love autocorrect

**Comment by Steveb1968** [comment]
That's weird, I've never run into that before.
Can you link to a debug log while you trying to add these videos please?
It would be nice to have a look at [MediaInfo](https://mediaarea.net/en/MediaInfo) also. :)

**Comment by montajd** [comment]
Just looking at the video formats of all of my videos, the two shows that aren't showing up are mp4 where the ones that are showing up are everything else, ts, avi, mkv.  Maybe it has to do with that? When you start the addon and its querying the database, the two shows are the only ones is fails to query.

**Comment by Steveb1968** [comment]
I'm assuming you've  got this sorted?
I have no problem with any of my mp4 videos.
If not post a Debug with some media info please.
Cheers.

**Comment by montajd** [comment]
Unfortunately never did, just ended up creating smart playlists for each show and getting rid of pseudoTV. Thanks though, I will miss using it


Sent from Mail for Windows 10
