### ISSUE TITLE
Problem with Directory Channels

### ISSUE THREAD

**Issue by Cothageris** [Steveb1968/script.pseudotv#20]
I've been having some troubles getting directory channels to work.  From my trouble shooting, directory channels will work for me only if the folder contains around 30 videos or less.  Any more than that and the "updating channel" progress bar freezes and causes me to have to terminate Kodi with task manager.  I was wondering if you would know of a fix or workaround?

**Comment by fnord12** [comment]
For what it's worth, I have a directory channel with about 500 videos in it and it works fine.  Maybe there's something wrong with a specific video or there's a problem with intermittent access to the directory?

**Comment by Cothageris** [comment]
I was worried it might be a problem like that.  They are all stored on an external hard drive.  I had previously been using psuedotv live and hadn't had a problem with directories, just a bunch of other bugs.  Any idea on how to troubleshoot it?  I've used several different folders with different sets of videos at this point and it's only the amount of videos that seems to be causing the problem.  Though I'm sure it only takes one bad one to spoil the batch.

**Comment by Cothageris** [comment]
Hello Again,

So about a month later I just happened to figure it out.  There where characters in the file name that psuedotv didn't like.  Specifically a long dash that was in a few files and Japanese characters that were in another file name. 

I haven't weeded out all the problem file names yet but here's how I figured it out in case anyone else has this problem.  So psuedotv would hang on channel load up whenever it gets to one of these weird file names.  I alt tabbed out of kodi and went to the folder where the files were.  I then tried to move all those files and it would move all but the problem file saying "this file is currently in use."  
After that I just had to close out of kodi (ctrl+alt+del) and change the file name.  Not a great work around for android or pi users but it's how I figured out the problem.

**Comment by fnord12** [comment]
This is definitely a (minor) problem with the latest version.  As noted above, I have a directory channel with a lot of files - music videos - and I was behind a version or two.  Recently I upgraded to the current version, and my pseudoTV  was locking up on the directory channel.  I turned on logging and found it was locking up on a Bjork video because of umlauts in the file name.  It seems any non-standard ASCII will break it, even, as Cothageris noted, long dashes.  It's easy enough to rename them all, but just wanted to highlight the issue and note that the problems seems to have been introduced with the latest version.

**Comment by Steveb1968** [comment]
I take a closer look at this for sure!

**Comment by gonzo90017** [comment]
Upgrading to 2.4.5 I ran into this issue. So I can confirm that this issue was not present in 2.4.4.

**Comment by Steveb1968** [comment]
Looking back I think I removed a Try loop, so the files causing the error would have skipped.. sorry I can fix that. :)

**Comment by Steveb1968** [comment]
I think I fixed this. If you could test please.

**Comment by fnord12** [comment]
I added back my umlauts and tested with a few em-dashes and other characters and it all seems good!

**Comment by Steveb1968** [comment]
Cheers mate.
