### ISSUE TITLE
PseudoTV keeps resetting channels

### ISSUE THREAD

**Issue by gonzo90017** [Steveb1968/script.pseudotv#21]
Settings:
Time between channel resets set to never 
Force Resume Mode
Pause When Not Watching
Play TV Shows in order

Channels keep resetting on newer versions. The last version that worked properly was 2.4.4. 

Let me know what files you need to help you get to the bottom of this.

**Comment by Steveb1968** [comment]
Hi guys, sorry for the lack of progress but real life sometimes kicks you in the nuts!!

**Comment by julestop** [comment]
I think I am getting the same behaviour... it resets the channel that i was last playing to the beginning of the movie or episode... i tried everything I could to force real time... but it works for all channels except the one that was playing when closing the app.

**Comment by gonzo90017** [comment]
The thing that "mostly" worked for me is this:
Setting> General>
Force Channel Reset on next start: Off
Time between channel resets: Never

I'm also on version 2.4.4 since I found this version to be the one where this issue appears the least. I've yet to try the newest versions. But will give them a try once I backup my current setup in case this still pops up.
