### ISSUE TITLE
Add year info for movies + default ep info (SxEP)

### ISSUE THREAD

**Issue by gonzo90017** [Steveb1968/script.pseudotv#23]
Just wondering if this is optional? I setup pseudotv to not have season and episode number showing since I think it looks a lot cleaner (like a traditional tv guide) when only the show name is visible.

**Comment by Steveb1968** [comment]
Yea for sure mate I can do that. I'll add it to the list.

**Comment by Steveb1968** [comment]
Just pushed option for this in visual settings if you would like to test. :)
