### ISSUE TITLE
Double quotes in description

### ISSUE THREAD

**Issue by fnord12** [Steveb1968/script.pseudotv#24]
Small thing, but it seems that when there is more than one set of double quotes in a movie/show description, the final quote is replaced with a slash and the rest of the description doesn't display in the episode guide.

See screenshot: http://www.supermegamonkey.net/kodi/PseudoQuote.png

Not a big deal, obviously.    PseudoTV continues to be awesome.  Thanks for all the work you do.

**Comment by Steveb1968** [comment]
Hi mate, yea that's a strange one. Had a quick look at the code but couldn't see anything obvious.
I edited a m3u list and added double quotes and that displayed fine.
Then I edited the db data description directly using DB browser for SQLite and then forced a channel reset and that displayed fine.
So I'm stumped.. :)

**Comment by Steveb1968** [comment]
Hi mate, just had a clean up in this area and I think I could of found the issue your describing. I will push a update later tomorrow.
