### ISSUE TITLE
Help? 

### ISSUE THREAD

**Issue by weebl101** [Steveb1968/script.pseudotv#25]
I am trying to figure out where to put the boolean condition to hide the seek panel whilst using Pseudotv. Can anyone help? 

Sorry if this is not the right spot to post

**Comment by fnord12** [comment]
weebl101, i don't have an answer to your question, but i found it useful to get rid of the seek bar altogether, which you can do by deleting (or renaming) the DialogSeekBar.xml file in your addons/[skin]/720p folder.

**Comment by Steveb1968** [comment]
@weebl101 Yea mate I'll gladly give you some guidance. Just need to know which skin your using.

**Comment by weebl101** [comment]
@steveb1968 I am using Titan Skin

**Comment by Steveb1968** [comment]
@weebl101 Hi mate, can't see Titan in the Leia repo so I had a look at the code on Github.
Basically all you need to do is add..

<visible>String.IsEmpty(Window(home).Property(PseudoTVRunning))</visible>

To DialogSeekBar.xml You can place it at the top of the xml just below the <window> line along with the other visible condition or you could add it to the first <control type="group"> just above the comment 
That should render the whole xml mute while PseudoTV is running.

If you want to do individual controls just add the bool to the controls separately or wrap a bunch in a control group and add the bool to the group.
