### ISSUE TITLE
Show info when changing channels bug

### ISSUE THREAD

**Issue by gonzo90017** [Steveb1968/script.pseudotv#28]
In version 2.4.4 whenever I changed the channel I would get the info box immediately and it would last around 5 seconds. In version 2.4.5 the info box takes about 2 seconds to appear and then it's only visible very briefly (maybe for half a second).

**Comment by dshokouhi** [comment]
Seeing this as well, maybe we can allow the user to set the timeout for the info box? I was previously using PTVL so there are some features I miss such as the timeout and also being able to start over a video with the ok button.

**Comment by Steveb1968** [comment]
Pushed a fix for this. Set it to 10 sec which is what it should be. It was set to 3 sec, I must have been testing something and forgot to set it back. :)
Will think about a user setting for this. I personally don't use this feature.

**Comment by Steveb1968** [comment]
Added a duration setting for this, default is 10sec
