### ISSUE TITLE
Clarification on how Channel Sharing works?

### ISSUE THREAD

**Issue by Espionage724** [Steveb1968/script.pseudotv#29]
I've set-up 4 different Kodi instances with PTV (master), enabled Channel Sharing on all of them, and pointed them to a folder on my NAS that I have added as a location from Kodi.

I set-up the 3 Kodi instances within a short period of time (maybe about 5-10 minutes between starts) and started them up with Channel Sharing one at a time, but all 3 instances looked to have different show times on their guides. If I recall correctly, the folder I used for the channel sharing on my NAS was empty.

I checked some hours later and noticed a settings2.xml in the channel sharing folder. It seems to list channel names, but nothing really specific with my media like titles or filenames (not sure if it's supposed to). I'm unsure if the 4th instance shares a channel guide with any of the other instances.

Is there any detailed information as to how to use and set-up channel sharing?

**Comment by Steveb1968** [comment]
To be honest I haven't used this feature in a long time. First step is to set up one instance of kodi with channel sharing enabled, we'll call it Master. :) start it, let it run for a while then close/stop it. Now you should have a "cache" folder with all your *.m3u channels and a settings2.xml in your shared folder. Now start the Master again this will lock the shared folder data so other clients can't alter it. Now start your client instances on PseudoTV and they should read the channel info from the shared folder and use it to create the channel list. Once this is set up it shouldn't matter which client you start first, it will lock the files and the rest of the clients will get what there given. (first in last out sort of thing). It's very basic and probably not the best way to go about it.. :)
