### ISSUE TITLE
EPG not Displaying

### ISSUE THREAD

**Issue by girmboto** [Steveb1968/script.pseudotv#30]
I've installed PseudoTV and set up some channels but i can't seem to get the EPG to display. Using Kodi 18.3 with the default skin. Is there something else i need to do to get it to show up?
The channels appear to be working but I have no idea why the EPG isn't. Any help would be appreciated.
Thanks Grimboto

**Comment by Steveb1968** [comment]
Hi mate, just tested Kodi 18.3 with the default skin and the EPG displayed ok on my end. Not sure what else to say. May be someone else with this issue can chime in. :)

**Comment by girmboto** [comment]
I fresh install of Kodi fixed the issue thanks for the reply
