### ISSUE TITLE
Certain videos not being detected in Directory Channels

### ISSUE THREAD

**Issue by retr0type** [Steveb1968/script.pseudotv#31]
I am trying to create a commercial channel to interleave into my main channel. I found a long compilation of commercials on YouTube and painstakingly split it into individual commercials (about 180 or so). I used Cyberlink PowerDirector encode each one. They are .mp4 files encoded with H.264.

PseudoTV will not play them at all. What's interesting is that I made a dedicated bumper channel, and converted individual bumper files straight from YouTube using a YouTube downloader site (y2mate.com) and those files play without issue.  

I have tried re-encoding them with Handbrake, created .nfo files using tinyMediaManager and even tried writing metadata to them using MetaX, but they simply will not detect. They play fine in Kodi, so I know they are readable.

Any help would be appreciated!

**Comment by dshokouhi** [comment]
There is an option to skip short videos, maybe try to disable that?  I would also look at the logs during this time as well to see if something else stands out

**Comment by Steveb1968** [comment]
Prob vid encoding/editing issue. Directory vids like this get the VidParser treatment to get the duration. If there shoddy.. goodby.. :)
Maybe splitting the file stuffed up the file header the parser is looking for?
