### ISSUE TITLE
crash when switching channels

### ISSUE THREAD

**Issue by mayson14** [Steveb1968/script.pseudotv#32]
Running Leia 18.3 on windows 64bit install
library is powered by emby

im not sure what else is could be unique about my setup. i tried to turn on debug logging to get some logs to share, but didnt have any luck with that.. 

Pseudotv loads and starts a show, pressing enter shows the guide.  but when selecting a different channel or pressing up or down to change channels causes the addon to close and sends me back to the kodi UI.

I would LOVE to use this.. i hope theres some help for me out there!

Let me know what logs or info i can share here.  Thanks in advance

**Comment by mayson14** [comment]
I tried downgrading to 18.1

also tried installing 32bit version of kodi.

uninstalling and re-installing the addon each time.. 

same results.

**Comment by dshokouhi** [comment]
Try to skip the emby integration and add videos to your library directly and see if the issue surpasses.  Its possible that it just doesnt like the path that you are using.  Personally I opt to let Kodi maintain its own DB separate from emby/plex and I use trakt to keep the 2 in sync.

**Comment by Steveb1968** [comment]
This add-on works for your local library only!
