### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by Lunatixz** [Steveb1968/script.pseudotv#34]
Glad to see you are still maintaining the older project... why don't we join forces and work together to maintain a newer version I'm releasing soon? If you are interested please PM me on the Kodi forums.

P.S regardless of your decision I sent you a moderator invite a few months back to the r/PseudoTV subreddit, please consider accepting it... this way you can field questions related to your version.

**Comment by Steveb1968** [comment]
Cool mate, be in touch soon.

**Comment by Lunatixz** [comment]
Welcome aboard...
