### ISSUE TITLE
Info (i) key should be mapped to "info" button on remote

### ISSUE THREAD

**Issue by montajd** [Steveb1968/script.pseudotv#35]
Pretty straight forward, but it would be a blessing if you could also allow the "info" button on the remote to show currently playing info screen as well. I know I could achieve this with a keymapper add-on, but just seems like a no-brainer honestly. Any chance this could be implemented?

**Comment by Steveb1968** [comment]
It already is and has always been mapped that way. My RC6 remote works out of the box with Windows and LibreELEC with standard keymaps, as should most remotes.

**Comment by montajd** [comment]
Bizaar. I'm using the amazon fire TV remote and info button will show all the playback controls and movie titles while watching videos inside Kodi outside of the plug-in, just not the info for PsuedoTV

**Comment by montajd** [comment]
is your RC6 remote sending keyboard keys or actual remote commands?

**Comment by montajd** [comment]
nevermind, used keymap editor, and got it resolved. I believe that button is originally mapped to "context menu"
