### ISSUE TITLE
Subtitles on by default?

### ISSUE THREAD

**Issue by fnord12** [Steveb1968/script.pseudotv#37]
I've been running into a weird issue where subtitles seem to be activated by default in PseudoTV.  I thought this was a problem with the latest commits but I reverted to older code and it's still an issue, and I realized it started happening when I recently upgraded from Krypton to Leia.  But it only happens in PSTV - outside of PSTV the subtitles follow the normal rules I've set in System > Player > Languages (which used to be the case for PSTV, too).  I don't see anything in the PSTV code about subtitles specifically so I don't know if anything can be done?

**Comment by Steveb1968** [comment]
Yea that is weird, I don't think its anything to do with PseudoTV. It's just using the standard player, nothing has changed over the years.
I tested and my subtitle rules are followed while in PseudoTV. I do set it up for "Forced only" though. Sometimes embedded subs can badly muxed (default track set, "und" language flag in both audio and subs).
Then external sub such as srt and the like can also be a problem. I find forced only does the job for me. If I need subs for some reason and the video has subs available I just manually enable them.

**Comment by Steveb1968** [comment]
I've had a think about this and realize it can become a problem in some situations.
I can map the videoosd window to the context menu key/button for easy access of subtitle settings, only while PsuedoTV is running of course 😊 (exit the videoosd with 'back/escape').

Also if you want the toggle subs feature while in PseudoTV you can add a custom Keymap to "userdata/keymaps/" folder and add <t>ShowSubtitles</t> to the global section so the overlay window can pick it up..

`
<keymap>
    <global>
        <keyboard>
            <t>ShowSubtitles</t>
        </keyboard>
    </global>
</keymap>
`

**Comment by fnord12** [comment]
Thanks for the tips.  I do have a key mapped to ShowSubtitles; just annoying to have to push it almost every time I change a channel!  And the problem occurs even though I've got System > Player > Languages > Preferred... set to "None".  Weird, but it seems to be just my own special problem so feel free to close this.  I was hoping to learn if there was something about PSTV that would cause the problem to occur only through it and not when playing a video normally, but doesn't seem to be the case.

**Comment by Canuma** [comment]
I can confirm that behavior.
I have a small test videolibrary basically consisting of the same mkv file, which has 2 audiotracks and 2 subtitletracks. i took 2 of those files and modiefied them in mkvtoolnix, flagged one as forced and renamed one track as forced (but did not actually force it)
the result is, at the beginning, the player behaves as expected, i have also set kodisettings to show only forced subs. After switching through some channels, it starts to display the first subtitle (kodi does also memorize that, so if i play that file regularly it will start with that subtitle enabled). 
Could it be that threading causes that behaviour?

**Comment by Steveb1968** [comment]
I only get forced subs with "Forced only"! Unless I manually enable them, then Kodi will remember that subs are enabled for that file and display them until I disable them again.
Like I said above I think this is a Kodi/file issue, nothing PseudoTV is doing or can do about it.
