### ISSUE TITLE
Bug on Rule "Play TV Shows In Order"

### ISSUE THREAD

**Issue by rafaelvieiras** [Steveb1968/script.pseudotv#39]
I find a bug when create a channel and add Rule "Play TV Shows In Order".

This put epsodes in order like:
- S01EP01
- S01EP10
- S01EP11
- ...

**Comment by Steveb1968** [comment]
Thanks mate, I'll have a look into that.
ps
If everyone could state "Kodi Ver." and "OS" when reporting problems like this that would be great. ;)

**Comment by Technobob** [comment]
I'm having the same issue with existing channels. I've tried reapplying the rule, deleting the playlist, creating a new channel.
LibreELEC 9.1.501 Kodi 18.4

**Comment by Technobob** [comment]
The fix did not work for me and I had an issue installing this update had to wipe the app completely to get it installed, Kodi kept giving an error something about unable to read addon.xml from zip. Whats happing for me the shows are being played in order some what. An example the show Ridiculousness plays the first season in order then jumps to season 10 and plays 10 to 15 in order, it then goes back to season 2 and plays in order to season 9.  It looks like any shows that go beyond season 9 have the play order problem.

**Comment by Steveb1968** [comment]
I don't have a test library with that number of seasons so haven't rested it but hopefully the latest commit fixes the problem.

**Comment by Technobob** [comment]
Looks like its fixed thank you and thanks for keep this app alive. I prefer your version over Lunatixz I only need local playback and its been very stable, this is the first issue I've had and I've been using it for years. 

While I have your attention any chance for an option in settings to remove the TV and Movie tags on the EPG or tell me the file that generates them so I can modify it.

**Comment by Steveb1968** [comment]
I'm not following you there "TV and Movie tags" can you explain.

**Comment by Technobob** [comment]
The TV & Movie tags are what I call them they're added to the channel titles in the EPG so it would show ABC TV, NBC TV, Action Movies, Comedy Movies etc.... Its not a big deal I just think they're redundant I know what the channel is and you don't see that on cable and satellite box EPG's

Are you planning on developing any skins if thats possible

**Comment by Steveb1968** [comment]
If you mean the auto generated name of the channel then no but you can rename them in advanced settings "Set Channel Name".
As for developing skins that was once possible but not anymore sorry.

**Comment by Technobob** [comment]
I forgot all about that option its been so long since I setup all the channels and the rules, it looks like I've got lots of channels to rename, thanks for reminding me.

Skins are no big deal I thought I'd ask

**Comment by Steveb1968** [comment]
No probs mate.
Tip: If your using playlists the channel name is taken from that.
Not the file name (blabla.xps) but the <name>blabla</name> defined in the xps file. So getting that right could save some time.
The auto generated channel names like "Animation Movies" will have to be changed as stated above.
