### ISSUE TITLE
Channel Sharing not working

### ISSUE THREAD

**Issue by gonzo90017** [Steveb1968/script.pseudotv#4]
If I disable channel sharing. PseudoTV loads fine. This only happens when channel sharing is enabled:
https://paste.ubuntu.com/23657396/

**Comment by Steveb1968** [comment]
Thanks for the input. Are these two Issues related or are they reproducible separately?
Also what system and software do you use?
Will have a look after the holiday's.
Cheers.

**Comment by gonzo90017** [comment]
Both issues are not related.  I can reproduce them seperately. This issue happens on a Windows 7 (server) and Windows 8.1 (client). Both running Kodi 14.2.

**Comment by Steveb1968** [comment]
Sorry I dropped support for Kodi 14.x. Kodi v15 and above only!
If you use v14.x you will run into problems. I hope you understand, with updates to skin and code it makes it hard to please everyone. :)
