### ISSUE TITLE
Admin UX Enhancements

### ISSUE THREAD

**Issue by fnord12** [Steveb1968/script.pseudotv#48]
Since my Reset Watched pull request went over well, I'm also submitting some changes I've made in the Admin UI.  I think they are pretty useful, but feel free to reject if you don't want to add them for any reason.

-Replaces Up/Down arrow selection with pop-up menus.  This seems like a much faster way to pick the rules and will be especially useful if you have a lot of TV Shows, genres, etc.
-Alphabetizes TV Show list
-Enables mouse clicks for Advanced Config (previously only keyboard Enter button worked)
-A few minor tweaks to Advanced Config UI:
	-- Hide Cancel button on Advanced Rule screen since it doesn't actually cancel anything
	-- Move control ID #130 since it sat on top of #120, causing weird behavior when trying to enter config for Rule 1.
	-- Add an asterisk to the Advanced Setting button to indicate when Advanced Setting rules have been set
-Adds a context menu (i.e. right click) to the main channel list:
	-- Copy a channel
	-- Swap channels
	-- Insert a channel and push all subsequent channels down^
	-- Delete a channel and move all subsequent channels up^
	-- Clear a channel (this functionality already existed but wasn't exposed in UI)
	
^For Insert and Delete, the shuffling will occur until the first blank channel.  This is useful for if you have hidden interlaced channels higher up in your list; the shuffling won't affect the interlace settings.

**Comment by Steveb1968** [comment]
Nice work mate. Much better!
