### ISSUE TITLE
Hide OSD when in PseudoTV

### ISSUE THREAD

**Issue by gils001** [Steveb1968/script.pseudotv#59]
Would love a toggle to hide the Onscreen Display when changing channels or when playing the next video while in PseudoTV. The Seek Bar/OSD popping up is kid of distracting when flipping through channels or say a preprogrammed commercial plays after every show. Would be great If the OSD only pops up when pressing enter, pausing, or seeking.

**Comment by fnord12** [comment]
Take a look at the solutions in closed item #25.

**Comment by gils001** [comment]
> Not exactly what you're asking for, but take a look at the solutions in closed item #25.

Thanks for the reply. The reason for my request was because I can't modify the default Estuary skin in Android (I am using an Nvidia Shield) without root access. But I believe another non root solution to this would be to make a new skin from Estuary and install it so that I can access its folder and modify the DialogueSeekBar.xml. Thanks again for the help. Would love to keep this up as an enhancement request, but it's your call.

**Comment by fnord12** [comment]
This is Steveb1968's project and i think he's walked away from things for the time being (see #50 ).  I try to help out with questions I can answer or fixing problems I introduced with the few things I submitted.  So you can leave this open but it probably won't be addressed soon, especially considering the available workaround.  (I definitely agree that the seeker bar is annoying, though.)

**Comment by gils001** [comment]
> This is Steveb1968's project and i think he's walked away from things for the time being (see #50 ). I try to help out with questions I can answer or fixing problems I introduced with the few things I submitted. So you can leave this open but it probably won't be addressed soon, especially considering the available workaround. (I definitely agree that the seeker bar is annoying, though.)

I believe you have explained the limitations of PseudoTV in that this is not possible without modifying a theme's xml file. I am closing this issue.
