### ISSUE TITLE
Krypton 17.0 Release: Channel Input Sends Timecode Input

### ISSUE THREAD

**Issue by jordanryle** [Steveb1968/script.pseudotv#6]
Channel can't be changed by inputting the number on a keypad anymore, as Kodi interprets it as a timecode to be set to instead. Typing the desired channel number and then pressing "Enter" causes Kodi to freeze, and can only be closed via Task Manager.

Windows 10 Anniversary x64
Kodi 17.0 Final Release
PseudoTV 2/1/17

**Comment by Steveb1968** [comment]
Thanks for the heads up, must admit its not a feature I use. I will defiantly try to fix that when I get some spare time. Causing a app to freeze is not good!

**Comment by jordanryle** [comment]
Thanks for the quick reply! No worry, just figured I'd report it. 

Cheers.

**Comment by Steveb1968** [comment]
Having trouble reproducing this issue.
Tested with below without any problems.

Win10 - Kodi 17.0
LibreELEC (Krypton) v7.95.3 BETA

**Comment by jordanryle** [comment]
Hmm...maybe it's a PVR-related issue then? I have attached a screenshot showing what is happening when I manually type in a channel. I was currently on channel 17 (just for example), and typed in 46, but as you can see, both PsuedoTV and the Kodi video player are taking in that input as Kodi wants to read that input as timecode like with normal non-PsuedoTV video playback. I couldn't find anything in the TV settings of Kodi that might disable this dual input, but maybe there is some other setting that can be disabled that would resolve this issue?

![2017-02-11 15_33_50-kodi](https://cloud.githubusercontent.com/assets/4150308/22858353/8e738224-f06f-11e6-9076-c1251c0423e2.jpg)

**Comment by Steveb1968** [comment]
The timecode you are seeing will not effect PseudoTV as there is a overlay window that grabs all the input and shows the media info. The timecode is a skin visible condition, it is usually found in VideoFullScreen.xml.
If your up for some skin modding you can add.. 

<visible>String.IsEmpty(Window(home).Property(PseudoTVRunning))</visible>

to hide it when PsuedoTV is running. Just look for $INFO[Player.SeekNumeric] and add it to the control in question.

I just hard coded the channel change delay and set it to 500ms. This is one of the reasons some systems can crash on channel change.

**Comment by jordanryle** [comment]
Dude you are the best! Downloaded the new code, and added the line to VideoFullScreen.xml and it's good as new! The only thing now is if you accidentally type a channel that doesn't exist, it'll only change the timecode without changing a channel, but that really won't affect me, and the add-on works now which is great! Thanks for all of your help!
