### ISSUE TITLE
Overlay opens and closed immediately

### ISSUE THREAD

**Issue by Tropps87** [Steveb1968/script.pseudotv#60]
I have an issue that happens quite frequently. I'll start PseudoTV and when I open the channel overlay, it shows for a split second and goes away. Then it will no longer open by pressing the button. In fact, no commands then work. I'm unable to exit or have any sort of response. The video continues to play but the only way out is to force close Kodi. This happens on both FireTV and Windows.

**Comment by fnord12** [comment]
That definitely sounds like PSTV is crashing.  You will probably find an Exception error in your log.  If not, please activate debugging in Kodi's System area and then reproduce the problem.  See instructions for that here: https://kodi.wiki/view/Log_file

After you do that, please post a new issue with those details on my branch: https://github.com/fnord12/script.pseudotv

PS I'm assuming you're not on Kodi 19/Matrix.

**Comment by Tropps87** [comment]
Thanks! I switched to your new branch and it no longer happens.
