### ISSUE TITLE
Movies always restart when external subtitle file is present

### ISSUE THREAD

**Issue by fnord12** [Steveb1968/script.pseudotv#8]
First: Thank you so much for this amazing program.

I have run into one issue: when an .srt file exists in a folder with a movie or television show, that show will always restart from the beginning every time you change to its channel.  This is regardless of whether things are set to Resume or Realtime or (as far as I can tell) any other settings.

Not a big deal.  Just wanted to make you aware of it if you weren't already.

I'm on Windows 10 and using Kodi 16.1 and I've confirmed the same behavior on Windows 7 for what it's worth.

**Comment by Steveb1968** [comment]
Thanks :)
Yep, I've heard of this problem before and run into it myself on a limited number of occasions (don't have to many vids with .srt files).
Give Kodi 17.1 a try if possible, with the improved video player updates this has killed a lot of these issues.
Cheers
